### ISSUE TITLE
Add Labyrinth Zone's Underwater Palette to the editable palettes

### ISSUE THREAD

**Issue by Samusaran2** [maxim-zhao/STH1EDWV#13]
Labyrinth Zone's Underwater Palette is currently unable to be edited within the editor, which sucks. The offsets for it are from 24B to 26A. (It could be easily added to the 'Other Art' section)

**Comment by Samusaran2** [comment]
Additional discovery I've just made right now: There is also (For some bizarre reason) a different underwater palette used for Act 3. This one goes from 26B to 28A. Please add them both to the program. Thanks!

**Comment by maxim-zhao** [comment]
Covered by All Palettes. Underwater palettes are shared by all levels with HasWater = True.
