### ISSUE TITLE
Add skybase lightning palettes

### ISSUE THREAD

**Issue by slogra7** [maxim-zhao/STH1EDWV#18]
Please add the lighting palettes for Skybase 1.
You "simply" have to extend the range of your current palettes, because all palettes are in a sequence.

See "palettes" at http://info.sonicretro.org/SCHG:Sonic_the_Hedgehog_(8-bit)#Master_System

All palettes are between offset 643E and 651E:
10 10 20 34 30 10 11 25 10 3D 39 3D 3F 24 00 38 
10 20 35 1B 16 2A 00 3F 01 03 3A 06 0F 27 15 00 
10 10 20 34 30 10 11 25 10 3D 39 3D 3F 24 00 38 
10 10 20 34 30 10 11 25 10 3F 3D 39 3D 24 00 38 
10 10 20 34 30 10 11 25 10 3D 3F 3D 39 24 00 38 
10 10 20 34 30 10 11 25 10 39 3D 3F 3D 24 00 38 
10 10 20 34 30 10 11 25 10 3D 39 3D 3F 24 00 38 
10 10 20 34 30 10 11 25 10 3F 3D 39 3D 24 00 38 
10 10 20 34 30 10 11 25 20 3D 3F 3D 39 24 00 38 
10 10 20 34 30 10 11 25 2A 39 3D 3F 3D 24 00 38 
10 10 20 34 30 10 11 25 2F 3D 39 3D 3F 24 00 38 
30 14 29 2E 3A 01 02 17 10 3F 3D 39 3D 0F 00 3F 
10 10 20 34 30 10 11 25 3F 3D 3F 3D 39 24 00 38
30 14 29 2E 3A 01 02 17 10 3F 3D 39 3D 0F 00 3F

Yup, that's a lot of palettes :)

**Comment by maxim-zhao** [comment]
Covered by the change that lets you edit all the palettes. Technically the lightning palette is shared by all levels with HasLightning = True, so it's not level-specific.
